### PR TITLE
replace stop with warning in check_dups

### PR DESCRIPTION
**Pull request by northeastloon**
There  are instances when where a 1:2 mapping (or more)  between clean and raw in encode_from may be desired.

### CODE REVIEW

**Comment by btskinner** [comment]
Can you say more about the situation you have in mind?

**Comment by northeastloon** [comment]
> 
> 
> Can you say more about the situation you have in mind?

For example, my raw labels are 1 (urban), 2 (rural:coastal), 3 (rural:inland). I would like to recode these simply to  1 (urban) and 2 (rural).

**Comment by btskinner** [comment]
I see. 

Everything should work if `unique(raw) >= unique(clean)` (which is your case), but not if `unique(raw) < unique(clean)`. There needs to be one unambiguous clean/new value for each raw/old value: otherwise, the mapping won't work. So we can't just get rid of the `stop()` b/c it needs to catch cases where the raw/old aren't unique.

There also has be a 1:1 mapping between clean/new values and their labels. The easiest way has been to require no duplicates across columns. But if there are duplicates in the clean/new and labels, the duplicates have to match each other. Testing them independently could result in cases where labels aren't unique within unique clean/new values.

It may be a bit before I can get to this. Feel up to taking a first pass at it?
The answer, I think, will be to make `check_dups()` in `utility_functions.R` more robust. Make it so it can take more than one column and test that if duplicates exist, they 1:1 match across the files.

**Comment by northeastloon** [comment]
> 
> 
> I see.
> 
> Everything should work if `unique(raw) >= unique(clean)` (which is your case), but not if `unique(raw) < unique(clean)`. There needs to be one unambiguous clean/new value for each raw/old value: otherwise, the mapping won't work. So we can't just get rid of the `stop()` b/c it needs to catch cases where the raw/old aren't unique.
> 
> There also has be a 1:1 mapping between clean/new values and their labels. The easiest way has been to require no duplicates across columns. But if there are duplicates in the clean/new and labels, the duplicates have to match each other. Testing them independently could result in cases where labels aren't unique within unique clean/new values.
> 
> It may be a bit before I can get to this. Feel up to taking a first pass at it?
> The answer, I think, will be to make `check_dups()` in `utility_functions.R` more robust. Make it so it can take more than one column and test that if duplicates exist, they 1:1 match across the files.

I have made some changes in response to your comments, although it could probably be made more robust. I have not made changes to the documentation, however. Thanks.

**Comment by btskinner** [comment]
I think it's more involved than your changes. It's not just about warning people. There has to be a check that the duplicates in the clean / label columns have a 1:1 mapping. If not, the function has to stop b/c the {labelled} package won't know how to assign the labels.

For example, I believe this crosswalk will pass the new `check_dups()` function, but will fail when it comes time to label:

|raw|clean|label|
|:---|:-----|:----|
|1|1|Urban|
|2|2|Urban|
|3|2|Rural|

The pseudocode has to be something like:

```r
check_dups <- function(cw, column_1, column_2 = NULL, message_code) {
    if (is.null(column_2)) { 
        do_what_it's_already_doing 
    } else {
        1. collapse into distinct pairs for column_1 and column_2
        2. confirm that when column_1 == x, column_2 == y (always and only)
        (this might just be collapsing for unique pairs and making sure that unique column_1 N == unique column_2 N == collapsed matrix number of rows)
   }
   based on results, either pass silently or stop with useful error
}
```
I'll take a look at this when I get some time unless you want to take another stab.

**Comment by northeastloon** [comment]
I inserted the following to check there is a 1:1 match on the labels.

```   
 if(!missing(column_2)) {
     n_val_lab <- dplyr::n_distinct(paste(cw[[column_1]], cw[[column_2]]))

       if(n_val_lab != dplyr::n_distinct(cw[[column_1]]) |  n_val_lab != dplyr::n_distinct(cw[[column_2]])) {
         stop("code values and labels do not match on a 1:1 basis") }
     }
```

**Comment by btskinner** [comment]
Thanks. I haven't forgotten about this. I'm just stacked up at the end of the semester. I hope to jump back into this in a day or so.

**Comment by btskinner** [comment]
I've made a number of changes and the package should do what you want now. I pushed to `northeastloon-feature/01` branch on my repo. Install the package from there (should be version 0.2.6) and see if it works. If all's well, I'll merge into the main branch and get set up for push to CRAN.

**Comment by northeastloon** [comment]
Sorry for getting back later on this. It's working for me. Thanks for your work!

**Comment by btskinner** [comment]
No problem! Glad it's working.

**Pull request merged**
